# Generated by Django 5.2.9 on 2026-05-31 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0059_examattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MannerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=70.0, verbose_name='매너점수')),
                ('tier', models.CharField(choices=[('best', '우수 판매자'), ('verified', '일반 인증'), ('caution', '주의 판매자'), ('blocked', '이용 제한')], default='verified', max_length=20, verbose_name='등급')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='총 평가 수')),
                ('good_count', models.PositiveIntegerField(default=0, verbose_name='좋았어요')),
                ('bad_count', models.PositiveIntegerField(default=0, verbose_name='아쉬웠어요')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manner_score', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '매너점수',
                'verbose_name_plural': '매너점수',
            },
        ),
        migrations.CreateModel(
            name='SellerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='신고 IP')),
                ('reason', models.CharField(choices=[('fake_photo', '사진과 실물 다름'), ('hidden_defect', '설명과 실제 상태 다름'), ('price_change', '가격 흥정 후 일방적 취소/변경'), ('broken_promise', '약속된 날짜/장소 불이행'), ('rude', '비매너/욕설/협박'), ('duplicate', '중복 등록/허위 매물'), ('other', '기타')], max_length=30, verbose_name='사유')),
                ('detail', models.TextField(blank=True, default='', verbose_name='상세')),
                ('is_handled', models.BooleanField(default=False, verbose_name='처리 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고일')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipment', verbose_name='매물')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_reports_filed', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
            options={
                'verbose_name': '판매자 신고',
                'verbose_name_plural': '판매자 신고',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('good', '좋았어요'), ('bad', '아쉬웠어요')], max_length=10, verbose_name='평가 유형')),
                ('comment', models.TextField(blank=True, default='', verbose_name='코멘트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('score_accuracy', models.PositiveSmallIntegerField(default=0, verbose_name='사진/설명 정확도')),
                ('score_response', models.PositiveSmallIntegerField(default=0, verbose_name='응답 속도')),
                ('score_promise', models.PositiveSmallIntegerField(default=0, verbose_name='약속 이행')),
                ('score_price', models.PositiveSmallIntegerField(default=0, verbose_name='가격 정직성')),
                ('score_disclosure', models.PositiveSmallIntegerField(default=0, verbose_name='하자 고지 성실도')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipment', verbose_name='매물')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='평가자')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
            options={
                'verbose_name': '판매자 거래 평가',
                'verbose_name_plural': '판매자 거래 평가',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewBadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('fake_photo', '허위 사진'), ('desc_exaggerate', '설명 과장'), ('broken_promise', '약속 불이행'), ('slow_response', '응답 느림'), ('overpriced', '가격 바가지'), ('rude', '비매너/불친절'), ('hidden_defect', '결함 은폐')], max_length=30, verbose_name='태그')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_tags', to='trust.sellerreview', verbose_name='평가')),
            ],
            options={
                'verbose_name': '불합리 태그',
                'verbose_name_plural': '불합리 태그',
            },
        ),
        migrations.AddConstraint(
            model_name='sellerreview',
            constraint=models.UniqueConstraint(condition=models.Q(('equipment__isnull', False), ('reviewer__isnull', False)), fields=('reviewer', 'equipment'), name='trust_unique_reviewer_equipment'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewbadtag',
            unique_together={('review', 'tag')},
        ),
    ]
