# Generated by Django 5.2.9 on 2026-06-18 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_key', models.CharField(db_index=True, max_length=64, verbose_name='토스 customerKey')),
                ('billing_key', models.CharField(max_length=200, verbose_name='토스 billingKey')),
                ('plan', models.CharField(choices=[('monthly', '월 자동결제'), ('yearly', '연 자동결제')], default='monthly', max_length=10)),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='청구 금액(원)')),
                ('card_company', models.CharField(blank=True, max_length=40, verbose_name='카드사')),
                ('card_number_masked', models.CharField(blank=True, max_length=40, verbose_name='카드번호(마스킹)')),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('CANCELLED', '해지'), ('FAILED', '청구 실패')], db_index=True, default='ACTIVE', max_length=12)),
                ('next_billing_at', models.DateTimeField(db_index=True, verbose_name='다음 청구 예정')),
                ('last_charged_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 청구 시각')),
                ('fail_count', models.PositiveSmallIntegerField(default=0, verbose_name='연속 청구 실패 수')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='해지 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '자동결제 빌링키',
                'verbose_name_plural': '자동결제 빌링키',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_billing_at'], name='billing_bil_status_b63daa_idx')],
            },
        ),
    ]
