# Generated by Django 5.2.9 on 2026-05-28 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='업체명')),
                ('equipment_types', models.JSONField(blank=True, default=list, verbose_name='취급 장비')),
                ('region', models.CharField(max_length=50, verbose_name='지역')),
                ('contact', models.CharField(max_length=50, verbose_name='연락처')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='주소')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='비고')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '임대 업체',
                'verbose_name_plural': '임대 업체',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RentalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('equipment_type', models.CharField(choices=[('excavator', '굴삭기'), ('forklift', '지게차'), ('dump', '덤프트럭'), ('loader', '스키로더·로더'), ('crane', '크레인'), ('attachment', '어태치먼트'), ('other', '기타')], default='excavator', max_length=20, verbose_name='기종')),
                ('region', models.CharField(max_length=50, verbose_name='지역')),
                ('rental_price', models.CharField(blank=True, default='', max_length=80, verbose_name='임대료')),
                ('rental_period', models.CharField(blank=True, default='', max_length=80, verbose_name='임대 기간')),
                ('contact', models.CharField(max_length=50, verbose_name='연락처')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='주소')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('description', models.TextField(blank=True, default='', verbose_name='상세 설명')),
                ('is_available', models.BooleanField(default=True, verbose_name='임대 가능')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '개인 임대',
                'verbose_name_plural': '개인 임대',
                'ordering': ['-created_at'],
            },
        ),
    ]
