# Generated by Django 5.2.9 on 2026-05-26 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0050_financeconsultation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django_session_key', models.CharField(db_index=True, max_length=40, verbose_name='세션 키')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='브라우저')),
                ('referer', models.TextField(blank=True, verbose_name='유입 URL')),
                ('landing_path', models.CharField(max_length=500, verbose_name='첫 방문 경로')),
                ('last_path', models.CharField(blank=True, max_length=500, verbose_name='마지막 경로')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='시작')),
                ('last_seen_at', models.DateTimeField(db_index=True, verbose_name='마지막 활동')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='체류(초)')),
                ('page_view_count', models.PositiveIntegerField(default=0, verbose_name='페이지 수')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_sessions', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '방문 세션',
                'verbose_name_plural': '7. 방문 세션(경로·체류)',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitPageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, verbose_name='경로')),
                ('query_string', models.CharField(blank=True, max_length=500, verbose_name='쿼리')),
                ('referer', models.TextField(blank=True, verbose_name='이전/유입 URL')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='조회 시각')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='다음 페이지로 이동할 때까지 머문 시간', null=True, verbose_name='체류(초)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='equipment.visitsession', verbose_name='방문 세션')),
            ],
            options={
                'verbose_name': '페이지 조회',
                'verbose_name_plural': '8. 페이지 조회 로그',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitsession',
            index=models.Index(fields=['-started_at'], name='equipment_v_started_7ba7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='visitsession',
            index=models.Index(fields=['django_session_key', '-last_seen_at'], name='equipment_v_django__746290_idx'),
        ),
        migrations.AddIndex(
            model_name='visitpagelog',
            index=models.Index(fields=['-viewed_at'], name='equipment_v_viewed__52e322_idx'),
        ),
        migrations.AddIndex(
            model_name='visitpagelog',
            index=models.Index(fields=['path', '-viewed_at'], name='equipment_v_path_288f86_idx'),
        ),
    ]
