# Generated by Django 5.2.9 on 2026-05-26 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0051_visit_analytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('question', '기출문제'), ('summary', '학과요약'), ('skill_tip', '실기팁'), ('review', '합격후기')], max_length=20)),
                ('equipment', models.CharField(choices=[('excavator', '굴삭기'), ('forklift', '지게차'), ('crane', '기중기'), ('common', '공통')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '자격증 시험 글',
                'verbose_name_plural': '자격증 시험',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='equipment.exampost')),
            ],
            options={
                'verbose_name': '자격증 시험 댓글',
                'verbose_name_plural': '자격증 시험 댓글',
                'ordering': ['created_at'],
            },
        ),
    ]
