# Generated by Django 5.2.9 on 2026-05-26 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0052_exampost_examcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def create_default_chat_rooms(apps, schema_editor):
        ChatRoom = apps.get_model('equipment', 'ChatRoom')
        for name in ('excavator', 'forklift', 'free'):
            ChatRoom.objects.get_or_create(name=name)

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('excavator', '굴삭기 시험 방'), ('forklift', '지게차 시험 방'), ('free', '자유 토크방')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': '수험생 채팅방',
                'verbose_name_plural': '수험생 채팅방',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='equipment.chatroom')),
            ],
            options={
                'verbose_name': '수험생 채팅 메시지',
                'verbose_name_plural': '수험생 채팅 메시지',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(create_default_chat_rooms, migrations.RunPython.noop),
    ]
