# Generated by Django 5.2.9 on 2026-05-26 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0053_student_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def create_default_community_boards(apps, schema_editor):
        CommunityBoard = apps.get_model('equipment', 'CommunityBoard')
        for name in ('excavator', 'forklift', 'free'):
            CommunityBoard.objects.get_or_create(name=name)

    operations = [
        migrations.CreateModel(
            name='CommunityBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('excavator', '굴삭기 시험'), ('forklift', '지게차 시험'), ('free', '자유 토크')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': '수험생 커뮤니티 게시판',
                'verbose_name_plural': '수험생 커뮤니티 게시판',
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='equipment.communityboard')),
            ],
            options={
                'verbose_name': '수험생 커뮤니티 글',
                'verbose_name_plural': '수험생 커뮤니티 글',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='equipment.communitypost')),
            ],
            options={
                'verbose_name': '수험생 커뮤니티 답글',
                'verbose_name_plural': '수험생 커뮤니티 답글',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.RunPython(create_default_community_boards, migrations.RunPython.noop),
    ]
