# Generated by Django 5.2.9 on 2026-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0054_community_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='board',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='communityreply',
            name='post',
        ),
        migrations.RemoveField(
            model_name='communityreply',
            name='author',
        ),
        migrations.AddField(
            model_name='exampost',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='유튜브 URL (시험동영상 유형일 때 입력)', null=True),
        ),
        migrations.AlterField(
            model_name='exampost',
            name='category',
            field=models.CharField(choices=[('question', '기출문제'), ('summary', '학과요약'), ('skill_tip', '실기팁'), ('review', '합격후기'), ('video', '시험동영상')], max_length=20),
        ),
        migrations.DeleteModel(
            name='CommunityBoard',
        ),
        migrations.DeleteModel(
            name='CommunityPost',
        ),
        migrations.DeleteModel(
            name='CommunityReply',
        ),
    ]
