# Generated by Django 5.2.9 on 2026-05-28 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0056_examattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('equipment_type', models.CharField(choices=[('excavator', '굴삭기'), ('forklift', '지게차'), ('crane', '기중기'), ('dump', '덤프트럭'), ('loader', '스키로더'), ('other', '기타')], max_length=20)),
                ('experience', models.CharField(choices=[('1', '1년 미만'), ('3', '1~3년'), ('5', '3~5년'), ('10', '5~10년'), ('10+', '10년 이상')], max_length=10)),
                ('region', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('day_rate', models.PositiveIntegerField(blank=True, help_text='일당(원), 없으면 협의', null=True)),
                ('contact', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('license', models.CharField(blank=True, default='', help_text='보유 자격증', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '중기 호출 기사',
                'verbose_name_plural': '중기 호출 기사',
                'ordering': ['-created_at'],
            },
        ),
    ]
