# Generated by Django 5.2.9 on 2026-05-31 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0058_profile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exam_files/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='equipment.exampost')),
            ],
            options={
                'verbose_name': '자격증 시험 첨부파일',
                'verbose_name_plural': '자격증 시험 첨부파일',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
