# Generated by Django 5.2.9 on 2026-06-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0060_profile_marketing_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attachment_tire_ad_active',
            field=models.BooleanField(default=False, help_text='승인된 업체만 상세 우측 광고란에 표시됩니다.', verbose_name='어태치먼트·타이어 광고 노출'),
        ),
    ]
