# Generated by Django 5.2.9 on 2026-06-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0061_profile_attachment_tire_ad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorCount',
        ),
        migrations.DeleteModel(
            name='VisitorSession',
        ),
    ]
