# Generated by Django 5.2.9 on 2026-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0062_remove_legacy_visitor_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
