# Generated by Django 5.2.9 on 2026-06-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0064_equipmentimage_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '장비 사진', 'verbose_name_plural': '3. 장비 사진 관리'},
        ),
        migrations.AddField(
            model_name='equipmentimage',
            name='watermarked',
            field=models.BooleanField(default=False, verbose_name='워터마크 적용됨'),
        ),
    ]
