# Generated by Django 5.2.9 on 2026-06-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0065_alter_equipmentimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='아이피 주소')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='요청 경로')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='접속 시각')),
            ],
            options={
                'verbose_name': '봇 차단 로그',
                'verbose_name_plural': '9. 봇 차단 로그',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['-accessed_at'], name='equipment_b_accesse_618950_idx'), models.Index(fields=['ip_address', '-accessed_at'], name='equipment_b_ip_addr_4d658c_idx')],
            },
        ),
    ]
