# Generated by Django 5.2.9 on 2026-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0066_botlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsshop',
            name='shop_kind',
            field=models.CharField(choices=[('as', 'AS센터'), ('parts', '부품점'), ('other', '기타')], default='parts', max_length=20, verbose_name='업체 유형'),
        ),
    ]
