from django.urls import path, re_path
from . import views
from chat import views as chat_views

urlpatterns = [
    # ── 구형 사이트 URL → 신규 URL (301 Permanent Redirect) ──
    re_path(
        r"^viewsale/굴삭기(?P<uid>[0-9]+)/?$",
        views.legacy_redirect_equipment_uid,
        name="legacy_viewsale_excavator",
    ),
    path(
        "viewsale/<int:uid>/",
        views.legacy_redirect_equipment_uid,
        name="legacy_viewsale_numeric",
    ),
    path(
        "attachment/<int:uid>/",
        views.legacy_redirect_equipment_uid,
        name="legacy_attachment_to_equipment",
    ),
    path(
        "job/<int:uid>/",
        views.legacy_redirect_job_uid,
        name="legacy_job_to_jobs",
    ),
    path(
        "community/<int:uid>/",
        views.legacy_redirect_community_to_board,
        name="legacy_community_to_board",
    ),
    # 신규 커뮤니티 상세 (구 /community/… 301 대상)
    path(
        "board/<int:pk>/",
        views.board_post_detail,
        name="board_detail",
    ),
    path('', views.index, name='index'),
    path('index/load-more/', views.index_load_more, name='index_load_more'),
    path('test/premium-experts/', views.premium_experts_test_view, name='premium_experts_test'),
    path('equipment/<int:pk>/', views.equipment_detail, name='equipment_detail'),
    path('equipment/create/', views.equipment_create, name='equipment_create'),
    path('new/', views.equipment_create, name='equipment_create_legacy'),
    path('jobs/', views.job_list, name='job_list'),
    path('jobs/create/', views.job_create, name='job_create'),
    path('jobs/exam/', views.exam_list, name='exam_list'),
    path('jobs/exam/videos/', views.exam_video_list, name='exam_video_list'),
    path('jobs/exam/create/', views.exam_create, name='exam_create'),
    path('jobs/exam/<int:pk>/', views.exam_detail, name='exam_detail'),
    path('jobs/exam/<int:pk>/edit/', views.exam_edit, name='exam_edit'),
    path('jobs/exam/<int:pk>/delete/', views.exam_delete, name='exam_delete'),
    path('jobs/<int:pk>/', views.job_detail, name='job_detail'),
    path('parts/', views.part_list, name='part_list'),
    path('parts/create/', views.part_create, name='part_create'),
    path('parts/<int:pk>/', views.part_detail, name='part_detail'),
    path('account/join/', views.join_choice, name='join_choice'),
    path('account/phone-send/', views.phone_send, name='phone_send'),
    path('account/phone-verify/', views.phone_verify, name='phone_verify_api'),
    path('account/join-check/', views.join_check, name='join_check'),
    path('account/legacy-convert/', views.legacy_convert_intro, name='legacy_convert_intro'),
    path('account/legacy-convert-send/', views.legacy_convert_send_code, name='legacy_convert_send_code'),
    path('account/signup-choices/', views.signup_choices, name='signup_choices'),
    path('signup/', views.signup, name='signup'),
    path('signup/done/', views.signup_done, name='signup_done'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('mypage/', views.my_page, name='my_page'),
    path('account/find-my-listings/', views.find_my_listings, name='find_my_listings'),
    path('billing/upgrade/', views.billing_upgrade, name='billing_upgrade'),
    path('account/convert/', views.legacy_convert, name='legacy_convert'),
    path('account/verify-phone/', views.verify_phone_page, name='phone_verify'),
    path('account/delete/', views.account_delete, name='account_delete'),
    path('equipment/<int:pk>/edit/', views.equipment_edit, name='equipment_edit'),
    path('equipment/<int:pk>/delete/', views.equipment_delete, name='equipment_delete'),
    path('equipment/<int:pk>/bump/', views.equipment_bump, name='equipment_bump'),
    path('equipment/<int:pk>/chat/', chat_views.equipment_chat_start, name='equipment_chat_start'),
    path('equipment/<int:pk>/favorite/', views.toggle_equipment_favorite, name='toggle_equipment_favorite'),
    path('equipment/author/<int:user_id>/', views.author_listings, name='author_listings'),
    path('parts/<int:pk>/favorite/', views.toggle_part_favorite, name='toggle_part_favorite'),
    path('jobs/<int:pk>/chat/', chat_views.job_chat_start, name='job_chat_start'),
    path('jobs/<int:pk>/edit/', views.job_edit, name='job_edit'),
    path('jobs/<int:pk>/delete/', views.job_delete, name='job_delete'),
    path('parts/<int:pk>/edit/', views.part_edit, name='part_edit'),
    path('parts/<int:pk>/delete/', views.part_delete, name='part_delete'),
    path('info/', views.excavator_info, name='excavator_info'),
    path('finance/', views.finance, name='finance'),
    path('parts-as/', views.parts_as, name='parts_as'),
    path('parts-as/register/', views.parts_as_register, name='parts_as_register'),
    path('parts-as/driver/', views.driver_list, name='driver_list'),
    path('parts-as/driver/register/', views.driver_register, name='driver_register'),
    path('parts-as/driver/<int:pk>/', views.driver_detail, name='driver_detail'),
    path('parts-as/driver/<int:pk>/edit/', views.driver_edit, name='driver_edit'),
    path('parts-as/driver/<int:pk>/delete/', views.driver_delete, name='driver_delete'),
    path('api/service-centers/', views.service_centers_api, name='service_centers_api'),
]
